#!/bin/sh
# 作用：在提交信息写入后执行
# 功能：
# 检查提交信息格式是否符合规范
# 要求格式：<type>(<scope>): <description>
# 何时触发：每次 git commit 时
commit_msg_file=$1

# 检查提交信息是否以指定的单词开头，并且描述不超过58个字符
if ! grep -qE "^(revert|feat|fix|docs|style|refactor|perf|test|chore|build|ci|merge|update)\(.+\):[[:space:]].{1,58}$" "$commit_msg_file"; then
  echo "❌:提交信息格式不符合规范，请参考以下格式:(或者您可以使用git cz命令,也可预览项目中的doc\GIT-README.md ~)"

  echo "类型范围(必填): 描述(不超过58个字符)"
  echo "示例: git commit -m 'merge(origin/bank-of-tianjin): 合并代码' && git push"
  exit 1
fi